# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [63]:
#Loading & inspecting data
df = pd.read_csv('AviationData.csv',encoding="latin-1")
df.head()

C:\Users\fkamau\AppData\Local\Temp\ipykernel_26440\2841254998.py:2: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('AviationData.csv',encoding="latin-1")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [64]:
df.shape

(88889, 31)

In [65]:
df.info

<bound method DataFrame.info of              Event.Id Investigation.Type Accident.Number  Event.Date  \
0      20001218X45444           Accident      SEA87LA080  1948-10-24
1      20001218X45447           Accident      LAX94LA336  1962-07-19
2      20061025X01555           Accident      NYC07LA005  1974-08-30
3      20001218X45448           Accident      LAX96LA321  1977-06-19
4      20041105X01764           Accident      CHI79FA064  1979-08-02
...               ...                ...             ...         ...
88884  20221227106491           Accident      ERA23LA093  2022-12-26
88885  20221227106494           Accident      ERA23LA095  2022-12-26
88886  20221227106497           Accident      WPR23LA075  2022-12-26
88887  20221227106498           Accident      WPR23LA076  2022-12-26
88888  20221230106513           Accident      ERA23LA097  2022-12-29

              Location        Country   Latitude  Longitude Airport.Code  \
0      MOOSE CREEK, ID  United States        NaN        NaN          NaN
1       BRIDGEPORT, CA  United States        NaN        NaN          NaN
2        Saltville, VA  United States  36.922223 -81.878056          NaN
3           EUREKA, CA  United States        NaN        NaN          NaN
4           Canton, OH  United States        NaN        NaN          NaN
...                ...            ...        ...        ...          ...
88884    Annapolis, MD  United States        NaN        NaN          NaN
88885      Hampton, NH  United States        NaN        NaN          NaN
88886       Payson, AZ  United States    341525N   1112021W          PAN
88887       Morgan, UT  United States        NaN        NaN          NaN
88888       Athens, GA  United States        NaN        NaN          NaN

      Airport.Name  ... Purpose.of.flight         Air.carrier  \
0              NaN  ...          Personal                 NaN
1              NaN  ...          Personal                 NaN
2              NaN  ...          Personal                 NaN
3              NaN  ...          Personal                 NaN
4              NaN  ...          Personal                 NaN
...            ...  ...               ...                 ...
88884          NaN  ...          Personal                 NaN
88885          NaN  ...               NaN                 NaN
88886       PAYSON  ...          Personal                 NaN
88887          NaN  ...          Personal  MC CESSNA 210N LLC
88888          NaN  ...          Personal                 NaN

      Total.Fatal.Injuries Total.Serious.Injuries Total.Minor.Injuries  \
0                      2.0                    0.0                  0.0
1                      4.0                    0.0                  0.0
2                      3.0                    NaN                  NaN
3                      2.0                    0.0                  0.0
4                      1.0                    2.0                  NaN
...                    ...                    ...                  ...
88884                  0.0                    1.0                  0.0
88885                  0.0                    0.0                  0.0
88886                  0.0                    0.0                  0.0
88887                  0.0                    0.0                  0.0
88888                  0.0                    1.0                  0.0

      Total.Uninjured Weather.Condition  Broad.phase.of.flight  \
0                 0.0               UNK                 Cruise
1                 0.0               UNK                Unknown
2                 NaN               IMC                 Cruise
3                 0.0               IMC                 Cruise
4                 0.0               VMC               Approach
...               ...               ...                    ...
88884             0.0               NaN                    NaN
88885             0.0               NaN                    NaN
88886             1.0               VMC                    NaN
88887             0.0               NaN                    NaN
88888             1.0               NaN                    NaN

        Report.Status Publication.Date
0      Probable Cause              NaN
1      Probable Cause       19-09-1996
2      Probable Cause       26-02-2007
3      Probable Cause       12-09-2000
4      Probable Cause       16-04-1980
...               ...              ...
88884             NaN       29-12-2022
88885             NaN              NaN
88886             NaN       27-12-2022
88887             NaN              NaN
88888             NaN       30-12-2022

[88889 rows x 31 columns]>

In [66]:
df.isna().sum().sort_values(ascending=False)

Schedule                  76307
Air.carrier               72241
FAR.Description           56866
Aircraft.Category         56602
Longitude                 54516
Latitude                  54507
Airport.Code              38757
Airport.Name              36185
Broad.phase.of.flight     27165
Publication.Date          13771
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Fatal.Injuries      11401
Engine.Type                7096
Report.Status              6384
Purpose.of.flight          6192
Number.of.Engines          6084
Total.Uninjured            5912
Weather.Condition          4492
Aircraft.damage            3194
Registration.Number        1382
Injury.Severity            1000
Country                     226
Amateur.Built               102
Model                        92
Make                         63
Location                     52
Investigation.Type            0
Event.Date                    0
Accident.Number               0
Event.Id                      0
dtype: int64

## Data Cleaning

In [67]:
#Percentage Misisng 
(df.isna().mean() * 100).sort_values(ascending=False)

Schedule                  85.845268
Air.carrier               81.271023
FAR.Description           63.974170
Aircraft.Category         63.677170
Longitude                 61.330423
Latitude                  61.320298
Airport.Code              43.601570
Airport.Name              40.708074
Broad.phase.of.flight     30.560587
Publication.Date          15.492356
Total.Serious.Injuries    14.073732
Total.Minor.Injuries      13.424608
Total.Fatal.Injuries      12.826109
Engine.Type                7.982990
Report.Status              7.181991
Purpose.of.flight          6.965991
Number.of.Engines          6.844491
Total.Uninjured            6.650992
Weather.Condition          5.053494
Aircraft.damage            3.593246
Registration.Number        1.554748
Injury.Severity            1.124999
Country                    0.254250
Amateur.Built              0.114750
Model                      0.103500
Make                       0.070875
Location                   0.058500
Investigation.Type         0.000000
Event.Date                 0.000000
Accident.Number            0.000000
Event.Id                   0.000000
dtype: float64

### Filtering aircrafts and events

In [68]:
#Check Duplicates
df.duplicated().sum()
#Summary statistics
df.describe(include='all')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
count,88889,88889,88889,88889,88837,88663,34382,34373,50132,52704,...,82697,16648,77488.000000,76379.000000,76956.000000,82977.000000,84397,61724,82505,75118
unique,87951,2,88863,14782,27758,219,25592,27156,10374,24870,...,26,13590,NaN,NaN,NaN,NaN,4,12,17074,2924
top,20001212X19172,Accident,CEN22LA149,1984-06-30,"ANCHORAGE, AK",United States,332739N,0112457W,NONE,Private,...,Personal,Pilot,NaN,NaN,NaN,NaN,VMC,Landing,Probable Cause,25-09-2020
freq,3,85015,2,25,434,82248,19,24,1488,240,...,49448,258,NaN,NaN,NaN,NaN,77303,15428,61754,17019
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.647855,0.279881,0.357061,5.325440,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.485960,1.544084,2.235625,27.913634,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,2.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,349.000000,161.000000,380.000000,699.000000,NaN,NaN,NaN,NaN

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [69]:
#Relevant columns,Filter out any reasonable imputations 
cols = [
    'Event.Date', 'Make', 'Model', 'Amateur.Built',
    'Total.Fatal.Injuries', 'Total.Serious.Injuries'
]

df[cols].head()
df[cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Date              88889 non-null  object
 1   Make                    88826 non-null  object
 2   Model                   88797 non-null  object
 3   Amateur.Built           88787 non-null  object
 4   Total.Fatal.Injuries    77488 non-null  float64
 5   Total.Serious.Injuries  76379 non-null  float64
dtypes: float64(2), object(4)
memory usage: 4.1+ MB

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [70]:
#view Columns 
print(df.columns.tolist())
#cleaning data and converting it to numeric
cols = [
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured'
]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
# Creating Total Occupants Column ~Assumption is below columns adds to Total occupancy
df['Total.Occupants'] = (
    df['Total.Fatal.Injuries'] +
    df['Total.Serious.Injuries'] +
    df['Total.Minor.Injuries'] +
    df['Total.Uninjured']
)
#Removing Invalid Rows
df = df[df['Total.Occupants'] > 0]
df = df.copy()

['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date']

In [71]:
#Creating Safety Metrics
df['fatality_rate'] = df['Total.Fatal.Injuries'] / df['Total.Occupants']

df['serious_injury_rate'] = df['Total.Serious.Injuries'] / df['Total.Occupants']

df['severe_injury_rate'] = (
    df['Total.Fatal.Injuries'] + df['Total.Serious.Injuries']
) / df['Total.Occupants']

In [72]:
#Fix Aircraft Damage Column
df['Aircraft.damage'] = df['Aircraft.damage'].str.strip()

df['is_destroyed'] = (df['Aircraft.damage'] == 'Destroyed').astype(int)

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [73]:
#Inpectting Aircraft Damage column
df['Aircraft.damage'].value_counts(dropna=False)

Aircraft.damage
Substantial    63879
Destroyed      18527
NaN             2590
Minor           2492
Unknown           92
Name: count, dtype: int64

In [74]:
#Stardardizing Text & Trimming
df['Aircraft.damage'] = (
    df['Aircraft.damage']
    .astype(str)
    .str.strip()
    .str.title()
)
#Handling missing values -Labeled unknown 
df['Aircraft.damage'] = df['Aircraft.damage'].replace('Nan', 'Unknown')
#creating a derived destrcution Column
df['is_destroyed'] = (df['Aircraft.damage'] == 'Destroyed').astype(int)

In [75]:
#Validating Results-Is destroyed
df[['Aircraft.damage', 'is_destroyed']].head()

  Aircraft.damage  is_destroyed
0       Destroyed             1
1       Destroyed             1
2       Destroyed             1
3       Destroyed             1
4       Destroyed             1

In [76]:
#Validating Results ~%total of destryoed vs not destroyed 
df['is_destroyed'].value_counts(normalize=True)

is_destroyed
0    0.788456
1    0.211544
Name: proportion, dtype: float64

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [77]:
#Inspect Make Column
df['Make'].value_counts().head(20)

Make
Cessna               22209
Piper                12016
CESSNA                4838
Beech                 4320
PIPER                 2813
Bell                  2117
Boeing                1441
Grumman               1094
Mooney                1092
BEECH                 1025
Robinson               943
Bellanca               886
Hughes                 794
BOEING                 705
Schweizer              627
Air Tractor            595
BELL                   569
Mcdonnell Douglas      502
Aeronca                486
Maule                  444
Name: count, dtype: int64

In [78]:
#Check Uniqueness
df['Make'].nunique()

8203

Cleaning tasks applied to the Make column:
#To avoid deplicate categories we have stratrdized text to  upper case
#Removed leading and trailing whitespaces 
#Replaced missing values with 'unknown'
#Grouped rare makes by filtering out those with fewer than 50 accidents records to enssure statistical robustness.

In [79]:
#Stardadize Test
df['Make'] = (
    df['Make']
    .astype(str)
    .str.strip()
    .str.upper()
)
#Replacing/Handling missing Values
df['Make'] = df['Make'].replace('NAN', 'UNKNOWN')
#view/recheck
df['Make'].value_counts().head(10)

Make
CESSNA      27047
PIPER       14829
BEECH        5345
BELL         2686
BOEING       2146
MOONEY       1331
ROBINSON     1208
GRUMMAN      1172
BELLANCA     1044
HUGHES        931
Name: count, dtype: int64

In [80]:
#count occurences 
make_counts = df['Make'].value_counts()
#Keep makes that has less than 50 accidents 
valid_makes = make_counts[make_counts >= 50].index
df = df[df['Make'].isin(valid_makes)].copy()
#Results Validation
df['Make'].value_counts().describe()

count       99.000000
mean       742.969697
std       3111.521875
min         50.000000
25%         73.500000
50%        136.000000
75%        321.500000
max      27047.000000
Name: count, dtype: float64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [81]:
# Drop rows where Model is missing-This is to allow proper grouping
#Rows with missing Model values are removed since aircraft identification is essential for analysis
df = df.dropna(subset=['Model']).copy()
#Cleaning Model column
df['Model'] = (
    df['Model']
    .astype(str)
    .str.strip()
    .str.upper()
)
#Inpect Model counts 
df['Model'].value_counts().head(20)

Model
152          2361
172          1740
172N         1160
PA-28-140     931
150           825
172M          797
172P          687
182           656
180           622
150M          585
PA-18         576
PA-28-180     572
PA-18-150     571
PA-28-161     565
PA-28-181     528
206B          516
PA-38-112     467
150L          460
G-164A        453
A36           439
Name: count, dtype: int64

In [82]:
#Check if Model is unique per Make 
#count how many makes each model appears under
model_make_counts = df.groupby('Model')['Make'].nunique()
# Models used by more than one manufacturer
model_make_counts[model_make_counts > 1].head()

Model
100        4
100-180    2
105        2
109        2
109A       2
Name: Make, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

Cleaning Tasks applied
#Stardardized Text fields, trimme whitespaces,uppercase -This is to guarantee consistency
#Replaced inconsistnet labels-e.g uknow-unknown
#Conversion of numneric columns to appropriate data types 
#Preserved missing values  to avoid introducing bias

In [83]:
#Sorts incosistnt casing -Engine.type column
df['Engine.Type'] = (
    df['Engine.Type']
    .astype(str)
    .str.strip()
    .str.upper()
)
#Inconssitent formating -Weather conditions 
df['Weather.Condition'] = (
    df['Weather.Condition']
    .astype(str)
    .str.strip()
    .str.upper()
)
#Stardadize
df['Weather.Condition'] = df['Weather.Condition'].replace({
    'UNK': 'UNKNOWN'
})
#Number of Engines (stored as object coupled with nonnumeric values)
df['Number.of.Engines'] = pd.to_numeric(
    df['Number.of.Engines'], errors='coerce'
)
#Purpose of flight(Many categories coupled with incosistinet naming)
df['Purpose.of.flight'] = (
    df['Purpose.of.flight']
    .astype(str)
    .str.strip()
    .str.upper()
)
#Broad.phase.of.flight column (mixed casing,missing values coupled with too many granular categories)
df['Broad.phase.of.flight'] = (
    df['Broad.phase.of.flight']
    .astype(str)
    .str.strip()
    .str.upper()
)
#stardize unknowns
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].replace({
    'UNK': 'UNKNOWN'
})
#Validating cleaning methods applied 
for col in [
    'Engine.Type', 'Weather.Condition', 
    'Number.of.Engines', 'Purpose.of.flight', 
    'Broad.phase.of.flight'
]:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False).head())

Engine.Type
Engine.Type
RECIPROCATING    58628
NAN               4729
TURBO SHAFT       3110
TURBO PROP        2872
TURBO FAN         2089
Name: count, dtype: int64

Weather.Condition
Weather.Condition
VMC        64124
IMC         5590
NAN         2851
UNKNOWN      950
Name: count, dtype: int64

Number.of.Engines
Number.of.Engines
1.0    57829
2.0     9915
NaN     4172
0.0      764
3.0      445
Name: count, dtype: int64

Purpose.of.flight
Purpose.of.flight
PERSONAL              39227
INSTRUCTIONAL          9836
UNKNOWN                6042
NAN                    4446
AERIAL APPLICATION     4291
Name: count, dtype: int64

Broad.phase.of.flight
Broad.phase.of.flight
NAN            19724
LANDING        13979
TAKEOFF        10555
CRUISE          9049
MANEUVERING     6719
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

Column removal criteria:
#Columns with more than 60% missing values were dropped, as they provide insufficient data for reliable analysis and could introduce bias

In [84]:
#Inpecting missingness (Columns-Columns with more than 60% missing values were dropped, as they provide insufficient data
# for reliable analysis and could introduce bias  )
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)
missing_pct

Schedule                  85.241107
Air.carrier               82.206352
FAR.Description           67.176767
Aircraft.Category         67.009454
Longitude                 64.452153
Latitude                  64.445351
Airport.Code              43.412909
Airport.Name              40.281575
Publication.Date          16.343603
Report.Status              5.904917
Number.of.Engines          5.675032
Registration.Number        1.382031
Country                    0.274774
Amateur.Built              0.076175
Location                   0.054411
Weather.Condition          0.000000
Broad.phase.of.flight      0.000000
Event.Id                   0.000000
Total.Minor.Injuries       0.000000
Total.Occupants            0.000000
fatality_rate              0.000000
serious_injury_rate        0.000000
severe_injury_rate         0.000000
Total.Uninjured            0.000000
Engine.Type                0.000000
Total.Serious.Injuries     0.000000
Total.Fatal.Injuries       0.000000
Purpose.of.flight          0.000000
Investigation.Type         0.000000
Model                      0.000000
Make                       0.000000
Aircraft.damage            0.000000
Injury.Severity            0.000000
Event.Date                 0.000000
Accident.Number            0.000000
is_destroyed               0.000000
dtype: float64

In [85]:
#Idnetify columns to drop columns as earlier indicated 
cols_to_drop = missing_pct[missing_pct > 60].index
cols_to_drop
#Drop them 
df = df.drop(columns=cols_to_drop).copy()

#Removed low-quality columns
#Improved dataset usability
#Reduced risk of misleading analysis

In [86]:
#Validate results
df.shape
df.isna().mean().sort_values(ascending=False).head()

Airport.Code         0.434129
Airport.Name         0.402816
Publication.Date     0.163436
Report.Status        0.059049
Number.of.Engines    0.056750
dtype: float64

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [87]:
#Saving cleaned aviation data
df.to_csv("cleaned_aviation_data.csv", index=False)